### ISSUE TITLE
Resizing of windows (responsiveness of new dashboard)

### ISSUE THREAD

**Issue by sreyaguha1** [amyxzhang/policykit#143]
Adjusting screen size leads to adjusted text

**Comment by rickygv99** [comment]
fixed most of the responsiveness issues with dashboard -- still need to fix button text

**Comment by rickygv99** [comment]
lets leave this up even after button text fixing bc will probably need to fix responsiveness as we add features to dashboard

**Comment by rickygv99** [comment]
closing because kind of broad right now -- been working on fixing responsiveness over time, not really any one issue
