### ISSUE TITLE
Stop treating actions as 'proposed' when they are not governed by any policy

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#290]
**Current behavior:**
Any `PlatformAction`s that are not governed––meaning there is no PlatformPolicy for which the `filter` block will return True for this action–– get created and saved with a Proposal with status `PROPOSED` ([code](https://github.com/amyxzhang/policykit/blob/f5763ba756cfebed08c1e2e9880b2e75581c058c/policykit/policyengine/models.py#L824)). From that point forward, they are continuously evaluated by the `consider_proposed_actions` task indefinitely–– or until a policy is created that applies to the action.

**Desired behavior**:
There are a few possible ways PolicyKit could handle PlatformActions that are not governed by any policy:
1. Set the attached proposal to PASSED
2. Set the attached proposal to FAILED
3. Do not create any Proposal for PlatformActions that do not have any governing Policies when they occur
4. Delete PlatformAction events that do not have any governing Policies when they occur

From discussion on [Slack](https://metagov.slack.com/archives/C01FSJD9W3Z/p1613752566029700) with @amyxzhang , it sounds like the ideal is to choose (1) or (2) as a default, and let the user configure it if they want to.

**Comment by amyxzhang** [comment]
Well I was also thinking that instead of us doing (1) or (2), the idea would be that communities would set (1) or (2) via a starter kit (meaning it would be part of a policy in all of the possible starter kits, and thus could evolve over time with the evolution governed by PK). This way we don't actually need to change any code in PK core or set system-wide defaults, which I'm trying to avoid.

**Comment by mashton** [comment]
Is it possible to represent 1 or 2 in a Policy right now, without changing any code? I can't figure out what that policy would look like.

If you're talking about including a default policy like [All Platform Actions Pass](https://github.com/amyxzhang/policykit/blob/f5763ba756cfebed08c1e2e9880b2e75581c058c/policykit/scripts/starterkits.py#L47-L59), I think it's not ideal because 1) it immediately introduces conflict with new policies that get added on top (a separate issue that needs to be addressed), 2)  the user could always change it, and end up in this situation of perpetually evaluated PlatformActions stacking up in the database. I was thinking we should change the code to actually protect against this situation happening.

**Comment by mashton** [comment]
closing in favor of https://github.com/amyxzhang/policykit/issues/542
