### ISSUE TITLE
Discord integration uses post ID as primary key for PlatformActions

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#345]
This may break the primary key uniqueness constraint when we have more than 1 active discord community, because post IDs  may not necessarily be unique across servers. Lets rename the field to `post_id` like I did here: https://github.com/amyxzhang/policykit/pull/300/commits/1644d65cbc65eb5f853e71e4c02d4698e8b9663c

https://github.com/amyxzhang/policykit/blob/ea3ac7e49078daade578726ec348e0f4c35d27f5/policykit/integrations/discord/views.py#L89-L93

this should be a django model field `post_id`
https://github.com/amyxzhang/policykit/blob/ea3ac7e49078daade578726ec348e0f4c35d27f5/policykit/integrations/discord/models.py#L169

**Comment by mashton** [comment]
@rickygv99 It's fixed in the Discourse integration, but not the Discord integration (https://github.com/amyxzhang/policykit/issues/332) but not Discord. I think this issue should still be open. Did you close it for another reason?

**Comment by rickygv99** [comment]
My bad; I thought I commented before closing but it looks like I forgot. Looked into the Discord message ID's and they are generated as Twitter snowflakes which are unique across the entire Discord platform, so they will be unique across servers.

**Comment by mashton** [comment]
Oh okay. I still think we should let Django handle the primary keys for all our PlatformActions, instead of relying on the uniqueness of identifiers from other systems. For a few reasons:
- Consistency: we use Django primary keys for all other platform actions. I don't see any benefit to using "Discord ID" just for `DiscordPostMessage`. Other Discord actions, like "rename channel" or "leave chat," may not have a unique key from discord either. If we use Django keys, we're being consistent across all actions.
- Not exposing Discord internals to users: in the `All actions` view in the PolicyKit UI we show a list of all actions and include their primary keys - which would include Discord IDs like "831994065499193354". We may want to rethink the fact that we're including primary keys here, but, at the very least I think we shouldn't expose the Discord ids to users.
- The recommended way in Django to set a custom primary key is to use `primary_key=True` on a field, not to override the `id` column https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields

**Comment by rickygv99** [comment]
Fixed in #352
