### ISSUE TITLE
Support multi-platform communities

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#384]

**Comment by mashton** [comment]
@amyxzhang @rickygv99 what do you think of this data model?


```
Community(Model):
- id: AutoField(unique)
- metagov_slug: CharField(unique)  # identifies this Community in Metagov

CommunityPlatform(PolymorphicModel):
- community: ForeignKey(Community)

SlackCommunityPlatform(CommunityPlatform)
- team_id: CharField(unique=True
- bot_id: CharField()

DiscordCommunityPlatform(CommunityPlatform)
- team_id: CharField(unique=True)

DiscourseCommunityPlatform(CommunityPlatform)
- team_id: CharField(unique=True)
```

The team_id is unique per platform, that's why it's defined in each subclass (this is how it's set up currently).

**Comment by amyxzhang** [comment]
Overall good. I think the naming is a little wordy, so I would move it to be PlatformCommunity and then SlackCommunity, DiscordCommunity, etc.

**Comment by mashton** [comment]
The renaming of `Community->PlatformCommunity` (and then a NEW model `Community`) was a lot harder thatn I expected @amyxzhang because Django migration system won't easily consider that to be a "model rename." I'd need to create a custom migration script to get it right and port everything over.
So, I gave up after a while and proceeded with `Community` and `ParentCommunity` instead. Is that OK? The model name is not user-facing.

**Comment by amyxzhang** [comment]
That's fine by me. Are we that worried about db migrations at this point? If it's time-consuming, I'd rather just save the time and remake the DB.

**Comment by mashton** [comment]
At this point there are a few instances of PolicyKit+Metagov, so each of us will have to do some form of manual data migration anyway so that we don't lose the PK Policies and the MG Plugin Community configuration (like stored API keys and so on). But yeah with this big of a change, I think you're right we should probably just reset "Django migrations" and perform the _actual_ data migration via custom scripts of downloading and uploading the data. Or else we will have a very complicated migration history in the code base.

**Comment by amyxzhang** [comment]
I'm also happy to wait until we've accumulated all the major DB changes we plan to make in the near term and do a big reset all in one go.

**Comment by mashton** [comment]
@amyxzhang here's an edge case I hit recently with https://github.com/amyxzhang/policykit/pull/438:

* User X goes to PolicyKit.org and installs PolicyKit to Slack workspace A. PolicyKit Community 001 is created.
* User Y goes to PolicyKit.org and installs PolicyKit to Discord server B. PolicyKit Community 002 is created.
* User Y goes to PolicyKit.org, logs in with Discord server B (a.k.a. Community 002). They go to "Settings" > "Add Integration" > "Slack". They are redirected to the Slack OAuth flow, and they select Workspace A for installation. 

🚨 What should the system do?

1. Allow the oauth installation, and create a new SlackCommunity connected to Community 002. There can't be multiple _installations_ of a single app in a single Slack workspace, however we could have two Slack Plugins (one for Community 001, another for Community 002) that are operating "independently" but as the same app. I don't think we should allow this, though, because it will be extremely confusing to users (is the bot acting on behalf of Comm 001 or Comm 002 with any given action? A single action is governed by 2 PolicyKit communities? yikes)
2. Reject the attempt to add Slack to Community 002, with a message like "PolicyKit is already installed to this workspace, go to 'log in with Slack' to access it. If you want to connect Slack to your current PolicyKit community (002), please delete/uninstall PolicyKit from your Slack workspace and try again."
    * This is simplest and hopefully most straightforward to the user. We don't give users capability to "merge" two existing PK Communities, we just allow people to progressively add _new_ integrations. (a.k.a. you can add more `PlatformCommunity`s to a `Community`, but you can't take two `Community`s and merge them together).
    * We don't have a way to delete communities in PolicyKit (yet) so the user would need to go to the Slack app management UI to uninstall the app.
3. It could reject the attempt to add Slack to Community 002, and **automatically merge** Community 001 and Community 002.
    * This can get tricky. Eg what do we do it C1 and C2 have both have SourceCred enabled but with different configs? etc.
4. Bring up some custom UI that lets the user merge communities.

I think we should implement (2). What do you think @amyxzhang?

**Comment by amyxzhang** [comment]
I agree with 2. Least confusing for users and easiest for us also, which is good because I think this will be rare so I don't want to build any special logic or UI at the moment.

**Comment by mashton** [comment]
Implementation is in-progress. This diagram shows the data model and relationships: https://lucid.app/lucidchart/4d388a65-b276-4ef1-8cd1-6e15f70b385f/edit?page=0_0#?referringapp=slack

**Comment by mashton** [comment]
I created a separate issue for no-platform communities: https://github.com/amyxzhang/policykit/issues/514

Closing this one, since multi-platform communities are supported now.
