### ISSUE TITLE
Split `notify_action` into 2 or more functions (performing a vote vs. notifying users)

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#413]
Currently the function `notify_action` is used to start a vote. It starts a choice vote if the action is of type ELECTION, otherwise it starts a boolean vote. This is the function signature for each platform community subclass:

```
# SlackCommunity
def notify_action(self, action, policy, users=None, post_type="channel", template=None, channel=None)
# DiscordCommunity
def notify_action(self, action, policy, users=None, template=None, channel=None)
# DiscourseCommunity
def notify_action(self, action, policy, users=None, template=None, topic_id=None)
# RedditCommunity
def notify_action(self, action, policy, users=None)
```

#### Proposed change

* Rename `notify_action` to `vote_on_action`, keep same parameters
* Add function `post_message` to PlatformCommunity subclasses with this signature:

      ```py
      # Slack, Discord
      def post_message(self, text, users=[], post_type="channel", channel=None)
      # Discourse
      def post_message(self, text, users=[], topic_id=None)
      # Reddit
      def post_message(self, text, users=[])
      ```

**Comment by mashton** [comment]
@amyxzhang what function names do you want for voting and messaging? I think you made a suggestion somewhere in slack but I can't find it now

**Comment by mashton** [comment]
Note to self:  update the function signature to make it possible for `post_message` to post a message in response to an existing thread on Slack.

**Comment by amyxzhang** [comment]
I forget where I put it. I think "vote_on_action" might be misinterpreted to mean making a vote so I think I proposed "initiate_vote" instead. 

And "post_message" sounds good.
