### ISSUE TITLE
Starter kits should initialize on PolicyKit initialization

### ISSUE THREAD

**Issue by rickygv99** [amyxzhang/policykit#431]
Right now, the user has to run a script to initialize starter kits. The user only runs this script once, and only on PolicyKit initialization. PolicyKit doesn't actually function unless this script is run. This script code should be run automatically when PolicyKit is set up -- the user should not have to run a separate script.

**Comment by mashton** [comment]
closed with https://github.com/amyxzhang/policykit/pull/435
