### ISSUE TITLE
Propose new API for performing x-platform actions/processes

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#440]
The current authoring API is not conducive to performing actions and votes on multiple platforms. This issue is to propose an alternative API that will sit on top of the new multi-platform data model https://github.com/amyxzhang/policykit/issues/384 

### Requirements
* As a policy author, I should be able to perform actions on any platform that is hooked up to my community
  * There shouldn't need to be a distinction between performing "actions that are governable" vs just "actions." For example `SourceCred.get_user_cred(...)` and `Slack.rename_channel(...)` could have the same syntax even though one is a governable PlatformAction and the other is just an api call to metagov
* As a policy author, I should be able to perform *one* vote on any voting-enabled-platform that is hooked up to my community
  * I should also be able to get the results of the vote at any time, with the users attached to the votes if available.
* As a policy author, I should be able to *propose* a new PlatformAction (aka "put it in the queue")
* As a policy author, I should NOT be able to access any actions/policies/data associated with other communities
* The syntax should be conducive to adding typehints/code completion.

### First pass
first attempt, rewriting one of our existing policies. This one is a "trigger" policy not a governing-action policy. 
```py
import datetime
import Discourse  # Class that gets all the available actions and processes dynamically added to it?
import OpenCollective
import TriggerEvent # Analog to PlatformAction (irreversible event)
import EvaluationState # TBD???

def filter(event: TriggerEvent):
    return event.platform == "opencollective" and event.type == "expense_created"


def notify(event: TriggerEvent):
    response = Discourse.initiate_vote(title="vote yes or no on expense", category=8, details="etc etc")
    poll_url = response.poll_url  # there are attributes on the response (?)

    expense_id = event.id  # there are attributes on the event, rather than just a json blob (?)
    message = f"Thank you for submitting an expense. Please vote at {poll_url}."
    response = OpenCollective.create_comment(expense_id=expense_id, raw=message)


def check(event: TriggerEvent, state: EvaluationState):
    yes_votes = state.get_yes_votes() # are these models? objects? classes? how do we access voter list?
    no_votes = state.get_no_votes()
    if state.get_time_elapsed() < datetime.timedelta(minutes=5):
	    return None # indicates pending..
    
    approved = yes_votes > no_votes
    # approve/reject the expense
    action = "APPROVED" if approved else "REJECT"
    OpenCollective.process_expense(expense_id=event.id, action=action)
    # notify the users
    message = f"Vote approved/rejected because X from policy Y"
    OpenCollective.create_comment(expense_id=event.id, raw=message)

    # return something to indicate completion?
    return True    

```

**Comment by mashton** [comment]
@amyxzhang here are my notes from our discussion just now, and I updated the requirements above
* Add req: you should be able to propose an action ("put it in the queue")
* Add req: no access to actions/policies that belong to other communities
* The `Process` above is some record that persists data relevant to the Action:Policy *evaluation.* For example it would replace "action.data.set(...)" and "action.proposal.get_yes_votes(..)" because those things are related to the specific evaluation. It is distinct from Proposal. It would get updated each time the action:policy are evaluated.
	* Possible names for this record: State, Context, Status, EvaluationState, ExecutionState, ..?
* PlatformCommunity---should everything be one?
	* what about twitter, perspective api
* Exposing metagov client library to policy author
* Option to store TriggerEvent in the DB or not. ScheduleTriggerEvent not stored / deleted after execution completes.
  * Eventually also want to enable deleting/archiving scrubbed PlatformActions after execution completes.
* platformactions delete when they are
* Need to not use `save()` to trigger policy evaluation. For some cases we will want to do it completely in memory and don't want to hit the DB or persist the event at all.
* Trigger policies can be at the platform and constitution level
* Possible data model changes:
  * Rename PlatformPolicy-> GoverningPolicy
  * Add TriggerPolicy
  * Add ConstitutionTriggerPolicy
  * Add TriggerEvent
  * Use a single table for PlatformAction+ConstitutionAction, make them proxy models
  * Use a single table for PlatformPolicy+ConstitutionPolicy+TriggerPolicy, make them proxy models

**Comment by mashton** [comment]
@amyxzhang after looking more closely at the data model, I don't see any reason to keep the `Proposal` record around. Everything that is currently stored in `Proposal` will also need to be stored in the `EvaluationState` (working name- see other suggestions above 🙂 ). Here's a proposal for `EvaluationState` record.

* The `EvaluationState` stores data about the evaluation of a policy+action pair.
* A new `EvaluationState` record is created when the filter block of a policy returns `True` for a given action, and we choose to continue the evaluation. If the policy has an asynchronous component, then all future evaluations of the action+policy pair will use the same EvaluationState.
* The celery task that currently re-runs proposed _actions_ will be changed to rerun evaluation for all statuses, like so:
    ```
    pending_evaluations = EvaluationState.objects.filter(status=PROPOSED)
    for p in pending_evaluations:
        engine.govern_action(p.action, p.policy)  #doesn't matter if it's constitution/platform/trigger/whatever)
    ```
   * This means that once an action moves into proposed state, it is "locked in" to keep evaluating against the same policy again and again until it passes or fails. That's different from how the engine currently works (it chooses a policy fresh every time, so it could be evaluating against different policies each time).
* The `EvaluationState` has convenience methods that are exposed to the policy author. These methods are for managing votes and async processes, and for storing data that needs to be saved across code blocks or across repeated evaluations.
* When policies use Metagov to perform async governance processes, the `callback_url` sent to Metagov is something like `policykit.org/api/internal/process/<id>` where the `id` is the primary key of an EvaluationState record. That way when PolicyKit receives the callback, it knows which EvaluationState the change pertains to. This tells us that something has changed (a vote was cast, for example) and includes the whole record (a serialized GovernanceProcess). We could store the Metagov process `outcome` as a JSONField on the EvaluationState, if we want to, OR we could just have the policies fetch the latest outcome from Metagov each time they evaluate. We can go with the latter for now.

#### Proposed Model, with comments inline

```py
class EvaluationState(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    """datetime that this action+policy were first evaluated"""

    status = models.CharField(choices=STATUS, max_length=10)
    """Status of the evaluation. One of PROPOSED, PASSED or FAILED.
    For trigger policies, the evaluation is considered 'PASSED' if it has completed
    and no exceptions were raised. Perhaps a more appropriate naming for
    Trigger policy evaluations would be PENDING/COMPLETED/FAILED, but I think
    we can stick with the current statuses since they map nicely."""

    policy = models.ForeignKey(Policy, models.CASCADE)
    """the policy that is being evaluated. in the future this might be versioned,
     so that all subsequent evaluations use the same version as the first evaluation."""

    action = models.ForeignKey(BaseAction, models.CASCADE)
    """the action or event that triggered the evaluation. ideally this can
    be a PlatformAction OR a ConstitutionAction OR a TriggerEvent"""

    governance_process_url = models.URLField(max_length=100, blank=True)
    """Metagov URL for the GovernanceProcess that is being used to make an 
    async decision about this evaluation"""

    data = models.OneToOneField(DataStore, models.CASCADE)
    """The datastore containing any additional data for the evaluation"""

    def get_time_elapsed(self):
        pass

    def get_all_boolean_votes(self, users=None):
        pass

    def get_yes_votes(self, users=None):
        pass

    def get_no_votes(self, users=None):
        pass

    def close_governance_process(self):
        # "close" process which might have an effect on external platform (like close and lock poll in Discourse)
        pass
```

**Comment by mashton** [comment]
### Proposed cross-platform authoring API v1

```py
import slack, discord, discourse, opencollective, sourcecred
import action, policy
import state

# EXAMPLE 1: performing a boolean vote on whether an action should pass or fail
users = slack.get_users()[0:5] # returns SlackUsers
slack.initiate_vote(action=action, policy=policy, users=users, template="please vote", channel=action.channel)

users = slack.get_users()[0:5] # returns DiscordUsers
discord.initiate_vote(action=action, policy=policy, users=users, template="please vote", channel=action.channel)

opencollective.initiate_vote(action=action, policy=policy, template="please vote")

# Getting the vote counts
yeses = state.get_yes_votes()   # returns BooleanVote queryset
yeses[0].user                   # is a CommunityUser

# EXAMPLE 2: messaging users
du = discord.get_users().first()
discord.post_message(text="hello", users=[du])

sus = slack.get_users()[0:3]
slack.post_message(text="hello", users=sus)

# EXAMPLE 3: performing platform-specific actions

# Creates a SlackKickConversation with community_origin=False, and initiator= some fake initiator indicating that is from a policy (has can_execute ???)
# We could use the "initiator" field to bypass governance
slack.kick_conversation(user=sus[0], channel="xyz")
# Creates a SlackScheduleMessage with community_origin=False
slack.schedule_message(initiator=sus[0], text="hello world", channel="xyz", post_at=1234)    # create a PA where the initiator is a policy

discord.rename_channel(channel=12345, name="new-name")

# EXAMPLE 4: making API calls
# each platform exposes a well-documented function for making any API call. parameters TBD.
slack.make_call(...)
opencollective.make_call(...)

```


The `import` statements at the top of the snipped show what's in scope. Here's a class that holds each object that's available to the policy author during a given execution. This "EvaluationScope" construct isn't visible to the policy author, they'll just be able to access each member in local scope.

```py
class EvaluationScope:
    action: Action = None
    policy: Policy = None

    # PolicyKit module for peforming constitution actions
    policykit = None
    
    # platform communities (with documented exposed functions like "post_message" and "initiate_vote")
    slack: SlackCommunity = None
    discord: DiscordCommunity = None
    discourse: DiscourseCommunity = None
    opencollective: OpenCollectiveCommunity = None
    sourcecred: SourceCredCommunity = None

    # evaluation state, used to access vote counts and store data
    state: EvaluationState = None

    # misc
    logger: EvaluationLogger = None

```

**Comment by mashton** [comment]
@amyxzhang  In order to support the wider range of voting capabilities offered by Metagov plugins, I propose splitting `initiate_vote` into `initiate_boolean_vote` and `initiate_choice_vote`:

```py
# CURRENT: user doesn't have the ability to decide whether to run a boolean vote or choice vote.
# if the proposal action is an action bundle, a single-choice vote occurrs. if it's a normal action, a boolean vote occurs.
slack.initiate_vote(proposal, text="please vote")

# PROPOSED: user must decide whether they want a boolean or choice vote. Rename "number vote" to "choice vote."
# We can add other options like deciding whether choice vote allows multiple choice, or whether boolean vote has an abstain option, etc.
slack.initiate_boolean_vote(proposal, text="please vote")
slack.initiate_choice_vote(proposal, text="please vote", options=["foo","bar","baz"])
# If 'options' not provided and proposal.action is a bundle, the engine does a choice vote on the bundled actions.
slack.initiate_choice_vote(proposal, text="please vote")
```

**Comment by thelastjosh** [comment]
Hi Miriam, quick question. Could you speak to how transferable this new API could be to Metagov, e.g. to a new "Platform" standard that can be consumed by multiple services / drivers beyond PK?

**Comment by mashton** [comment]
@thelastjosh it's possible that if we implement a Metagov Python library we could expose it directly to policy authors like this. @amyxzhang and I discussed that future possibility briefly. For example, the metagov library would have platform methods like `slack.post_message(text="", channel="")` and `opencollective.initiate_vote(title="", options=[..])` etc and that library is exposed directly to the policy author. I'm not sure that's realistic for PolicyKit, though, since PolicyKit does it's own data storage and has this added action/policy/proposal context that is used to infer some parameters.

**Comment by mashton** [comment]
Closing this issue, as the proposal is done and we're partially done implementing. These are the remaining implementation issues: 
https://github.com/amyxzhang/policykit/issues/459
https://github.com/amyxzhang/policykit/issues/460
https://github.com/amyxzhang/policykit/issues/458
