### ISSUE TITLE
backend db model to store generic policies/starter kits

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/policykit#51]
right now every policy is attached to a community, but we need a place to store generic policies that can then be instantiated as a communitypolicy/constitutionpolicy object.

could maybe also have the model store other aspects of the starter kit, such as default roles/permissions or other things if we eventually imagine having like >5 different versions of these---otherwise, we can just do it in the code if there aren't that many.

**Comment by ekim6767** [comment]
completed in #92
