### ISSUE TITLE
get slack username for users who don't sign in to policykit

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/policykit#6]
right now I can do actions in slack like postMessage but not have to go to policykit to log in for the first time for it to work. however, this means that policykit doesn't have a SlackUser object for me. We have the user_id from the event handler, so we can create a mostly empty SlackUser object to store the user_id. What would be good to get however is the actual username or readable name (for instance, when postMessage goes through but has to be posted by the Bot account, we can prepend the message with the actual poster's name)

There should be a way to call slack to get that info and populate it at the point where i create that user: https://api.slack.com/methods/users.profile.get

**Comment by ekim6767** [comment]
addressed in pull request 44
