### ISSUE TITLE
community policy creation allows for unnamed policies

### ISSUE THREAD

**Issue by ekim6767** [amyxzhang/policykit#87]
right now, the admin site allows for unnamed policies to be created, when executing the action "add community policy". Should prevent user from making policy until it is named

**Comment by AvianAnalyst** [comment]
Hello! I just recently found this project, but i'm absolutely in love. This seems like it shouldn't be too hard to fix, would it be cool for me to try to tackle this to get started with contributing for y'all?

**Comment by amyxzhang** [comment]
Absolutely @AvianAnalyst! Thank you so much and let me know if you have questions!

**Comment by rickygv99** [comment]
that would be amazing @AvianAnalyst !

**Comment by mashton** [comment]
this has been fixed
