### ISSUE TITLE
Get list of users at the start of integrating a slack

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/policykit#9]
we want to save the ids of all users stored in SlackUser (even if we don't have their access token) so that we can count their votes and assign them to juries, etc. even if they haven't logged in yet. This should happen at install time.

**Comment by amyxzhang** [comment]
related to #6

**Comment by amyxzhang** [comment]
when a user then goes to log in in PolicyKit we should be able to find their existing user object and not be creating duplicate users

**Comment by ekim6767** [comment]
Addressed in pull request 44
